# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: https://flash-forward-reviews.github.io
# baseurl: 
title: 'Flash Forward Reviews'
description: 'Great Reviews for Attractive People'
permalink: pretty
logo: /assets/logos/logo-flash-forward.png
logodark: /assets/logos/logo-flash-forward-grey.png
source-code: https://github.com/flash-forward-reviews/penguin

disqus:
  comments: true  # boolean type, the global switch for posts comments.
  shortname: flashforwardreviews # Fill with your Disqus shortname. â€º https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# Pagination
paginate: 5
paginate_path: blog/page:num

# Comments
comments: false

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Game Categories
  url: /categories/
- title: Search
  url: /search/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/ICONIC.png'
  32: '/assets/logos/ICONIC.png'
  96: '/assets/logos/ICONIC.png'
  120: '/assets/logos/ICONIC.png'
  144: '/assets/logos/ICONIC.png'
  180: '/assets/logos/ICONIC.png'
  512: '/assets/logos/ICONIC.png'
  1024: '/assets/logos/ICONIC.png'

# Collections
collections:
  posts:
    title: Posts
    output: true
    feature_text: |
      Flash-Forward Reviews
    feature_image: /assets/banner-flash-forward.png

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
      comments: true   # change to false to default to comments off site-wide
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap